name: aadi58002/metrics

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: aadi58002/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
